version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - .:/app  # Mount the current directory into the container's /app directory
    # environment: # Add your environment variables here.
    #   - FLASK_APP=order_tracking_app.py
    #   - FLASK_ENV=development
    # networks: # Add your networks here.
    #   - mynetwork

#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#networks:
# mynetwork:
#  driver: bridge

# volumes:
#  postgres_data: